__all__ = ["category_names", "job_names"]
category_names = [
    "misc_net",
    "gas_transport",
    "kids_pets",
    "home",
    "shopping_net",
    "food_dining",
    "personal_care",
    "grocery_pos",
    "entertainment",
    "shopping_pos",
    "misc_pos",
    "travel",
    "health_fitness",
    "grocery_net",
]

job_names = [
    "Information systems manager",
    "Secondary school teacher",
    "Barrister's clerk",
    "Politician's assistant",
    "Horticulturist, commercial",
    "Programmer, applications",
    "Television camera operator",
    "Call centre manager",
    "Chief Marketing Officer",
    "Buyer, industrial",
    "Armed forces logistics/support/administrative officer",
    "Pilot, airline",
    "Therapist, horticultural",
    "Dancer",
    "Ceramics designer",
    "Naval architect",
    "Engineer, agricultural",
    "Health service manager",
    "Sport and exercise psychologist",
    "Forensic psychologist",
    "Exhibition designer",
    "Nurse, children's",
    "Soil scientist",
    "Prison officer",
    "Economist",
    "Copywriter, advertising",
    "Television floor manager",
    "Lecturer, higher education",
    "Sales professional, IT",
    "Exhibitions officer, museum/gallery",
    "Freight forwarder",
    "Engineering geologist",
    "Surveyor, hydrographic",
    "Trade mark attorney",
    "Public relations account executive",
    "Engineer, site",
    "Race relations officer",
    "Podiatrist",
    "Clothing/textile technologist",
    "Retail merchandiser",
    "Engineer, civil (contracting)",
    "Make",
    "Advertising account executive",
    "Armed forces training and education officer",
    "Special educational needs teacher",
    "Special effects artist",
    "Corporate investment banker",
    "Immunologist",
    "Barrister",
    "Designer, interior/spatial",
    "Early years teacher",
    "Chief Executive Officer",
    "Mechanical engineer",
    "Administrator, education",
    "Engineer, electronics",
    "Estate manager/land agent",
    "Television/film/video producer",
    "Chiropodist",
    "Senior tax professional/tax inspector",
    "Airline pilot",
    "Engineer, petroleum",
    "Materials engineer",
    "Civil engineer, contracting",
    "Sales executive",
    "Editor, film/video",
    "Marketing executive",
    "Historic buildings inspector/conservation officer",
    "Higher education careers adviser",
    "Chief Financial Officer",
    "Editor, commissioning",
    "Financial trader",
    "Animal nutritionist",
    "Further education lecturer",
    "Clinical research associate",
    "Writer",
    "Air traffic controller",
    "Engineer, automotive",
    "Tourism officer",
    "Designer, industrial/product",
    "Broadcast presenter",
    "Quarry manager",
    "Careers information officer",
    "Cartographer",
    "Petroleum engineer",
    "Aid worker",
    "Database administrator",
    "Technical brewer",
    "Educational psychologist",
    "Engineer, building services",
    "Agricultural consultant",
    "Scientist, biomedical",
    "Probation officer",
    "Conservation officer, historic buildings",
    "Physiotherapist",
    "Equality and diversity officer",
    "Quantity surveyor",
    "Occupational hygienist",
    "Academic librarian",
    "Air broker",
    "Catering manager",
    "Licensed conveyancer",
    "Pharmacist, hospital",
    "Television production assistant",
    "Insurance underwriter",
    "English as a second language teacher",
    "Music tutor",
    "Programmer, multimedia",
    "Therapist, art",
    "Financial adviser",
    "Media planner",
    "Land/geomatics surveyor",
    "Architect",
    "Set designer",
    "Lawyer",
    "Administrator, arts",
    "Tax adviser",
    "Drilling engineer",
    "Administrator",
    "Community education officer",
    "IT trainer",
    "IT consultant",
    "Journalist, newspaper",
    "Psychologist, forensic",
    "Site engineer",
    "Curator",
    "Film/video editor",
    "Investment banker, corporate",
    "Geochemist",
    "Professor Emeritus",
    "Chemical engineer",
    "Fine artist",
    "Pension scheme manager",
    "Systems developer",
    "Firefighter",
    "Learning disability nurse",
    "Network engineer",
    "Sales promotion account executive",
    "Child psychotherapist",
    "Building surveyor",
    "Energy engineer",
    "Human resources officer",
    "Metallurgist",
    "Pharmacist, community",
    "Tour manager",
    "Paramedic",
    "Arboriculturist",
    "Dispensing optician",
    "Engineer, production",
    "Engineer, control and instrumentation",
    "Embryologist, clinical",
    "Paediatric nurse",
    "Radio producer",
    "Applications developer",
    "Local government officer",
    "Chief Strategy Officer",
    "Sub",
    "Orthoptist",
    "Lexicographer",
    "Press sub",
    "Chief Operating Officer",
    "Geoscientist",
    "Environmental consultant",
    "Commissioning editor",
    "Cytogeneticist",
    "Chartered legal executive (England and Wales)",
    "Civil Service fast streamer",
    "Presenter, broadcasting",
    "Fitness centre manager",
    "Development worker, community",
    "Wellsite geologist",
    "Ambulance person",
    "Psychotherapist",
    "Gaffer",
    "Radio broadcast assistant",
    "Training and development officer",
    "Seismic interpreter",
    "Counsellor",
    "Librarian, public",
    "Personnel officer",
    "Magazine features editor",
    "Horticultural consultant",
    "Buyer, retail",
    "Aeronautical engineer",
    "Education officer, museum",
    "Scientist, research (medical)",
    "Toxicologist",
    "Town planner",
    "Scientist, research (maths)",
    "Jewellery designer",
    "Hotel manager",
    "Facilities manager",
    "Plant breeder/geneticist",
    "Civil Service administrator",
    "Occupational therapist",
    "Diagnostic radiographer",
    "Conservator, museum/gallery",
    "Intelligence analyst",
    "Warden/ranger",
    "Animal technologist",
    "Furniture designer",
    "Claims inspector/assessor",
    "Industrial/product designer",
    "Glass blower/designer",
    "Armed forces technical officer",
    "Nature conservation officer",
    "Manufacturing engineer",
    "Exercise physiologist",
    "Designer, textile",
    "Geophysicist/field seismologist",
    "Surveyor, land/geomatics",
    "Risk analyst",
    "Development worker, international aid",
    "Audiological scientist",
    "Hydrologist",
    "Engineer, land",
    "Engineer, biomedical",
    "Teacher, secondary school",
    "Building control surveyor",
    "English as a foreign language teacher",
    "Leisure centre manager",
    "Emergency planning/management officer",
    "Chartered accountant",
    "Chartered public finance accountant",
    "Public affairs consultant",
    "Control and instrumentation engineer",
    "Trading standards officer",
    "Archaeologist",
    "Designer, exhibition/display",
    "Engineer, maintenance",
    "Insurance broker",
    "Research scientist (physical sciences)",
    "Science writer",
    "Psychiatrist",
    "Video editor",
    "Horticultural therapist",
    "Advertising account planner",
    "Music therapist",
    "Physiological scientist",
    "Teacher, primary school",
    "Doctor, general practice",
    "Physicist, medical",
    "Dealer",
    "Therapist, occupational",
    "Futures trader",
    "Accountant, chartered public finance",
    "Electrical engineer",
    "Commercial horticulturist",
    "Pensions consultant",
    "Records manager",
    "Doctor, hospital",
    "Engineer, broadcasting (operations)",
    "Colour technologist",
    "Environmental health practitioner",
    "Theatre manager",
    "Comptroller",
    "Optician, dispensing",
    "Social research officer, government",
    "Production assistant, radio",
    "Community pharmacist",
    "Production engineer",
    "Regulatory affairs officer",
    "Statistician",
    "Administrator, local government",
    "Telecommunications researcher",
    "Research scientist (medical)",
    "Administrator, charities/voluntary organisations",
    "General practice doctor",
    "Rural practice surveyor",
    "Education administrator",
    "Multimedia programmer",
    "Heritage manager",
    "TEFL teacher",
    "Phytotherapist",
    "Museum education officer",
    "Designer, ceramics/pottery",
    "Mudlogger",
    "Police officer",
    "Research officer, trade union",
    "Retail buyer",
    "Accounting technician",
    "Dance movement psychotherapist",
    "Theatre director",
    "Waste management officer",
    "Web designer",
    "Nurse, mental health",
    "Herpetologist",
    "Tourist information centre manager",
    "Radiographer, therapeutic",
    "Designer, jewellery",
    "Scientist, physiological",
    "Investment analyst",
    "Insurance risk surveyor",
    "Teacher, special educational needs",
    "Product designer",
    "Librarian, academic",
    "Mining engineer",
    "Stage manager",
    "Investment banker, operational",
    "Geneticist, molecular",
    "Medical physicist",
    "Product/process development scientist",
    "Arts development officer",
    "Charity fundraiser",
    "Land",
    "Teaching laboratory technician",
    "Acupuncturist",
    "Transport planner",
    "Forest/woodland manager",
    "Charity officer",
    "Herbalist",
    "Industrial buyer",
    "Medical sales representative",
    "Landscape architect",
    "Teacher, early years/pre",
    "Event organiser",
    "Conservator, furniture",
    "Hydrographic surveyor",
    "Producer, radio",
    "Psychologist, counselling",
    "Designer, furniture",
    "Theme park manager",
    "Hospital pharmacist",
    "Volunteer coordinator",
    "Pathologist",
    "Psychologist, sport and exercise",
    "Health visitor",
    "Programme researcher, broadcasting/film/video",
    "Counselling psychologist",
    "Operations geologist",
    "Chief of Staff",
    "Engineer, communications",
    "Engineer, mining",
    "Biochemist, clinical",
    "Scientist, clinical (histocompatibility and immunogenetics)",
    "Medical secretary",
    "Hospital doctor",
    "Location manager",
    "Mental health nurse",
    "Scientist, audiological",
    "Careers adviser",
    "Therapist, drama",
    "Accountant, chartered",
    "Social researcher",
    "Solicitor",
    "Travel agency manager",
    "Scientist, marine",
    "Artist",
    "Surveyor, minerals",
    "Patent attorney",
    "Chartered loss adjuster",
    "Scientific laboratory technician",
    "Interior and spatial designer",
    "Medical technical officer",
    "Broadcast engineer",
    "Fisheries officer",
    "Engineer, water",
    "Commercial/residential surveyor",
    "Engineer, structural",
    "Communications engineer",
    "Teacher, English as a foreign language",
    "Magazine journalist",
    "Community development worker",
    "Legal secretary",
    "Optometrist",
    "Psychologist, clinical",
    "Software engineer",
    "Oncologist",
    "Research officer, political party",
    "Information officer",
    "Cabin crew",
    "Geologist, engineering",
    "Outdoor activities/education manager",
    "Textile designer",
    "Learning mentor",
    "Minerals surveyor",
    "Clinical biochemist",
    "Maintenance engineer",
    "Market researcher",
    "Health physicist",
    "Biomedical engineer",
    "Associate Professor",
    "Electronics engineer",
    "Engineer, civil (consulting)",
    "Contractor",
    "Engineer, materials",
    "Visual merchandiser",
    "Production manager",
    "Structural engineer",
    "Amenity horticulturist",
    "Osteopath",
    "Press photographer",
    "Purchasing manager",
    "Camera operator",
    "Advice worker",
    "Insurance claims handler",
    "Furniture conservator/restorer",
    "Manufacturing systems engineer",
    "Copy",
    "Lecturer, further education",
    "Animator",
    "Surveyor, mining",
    "Retail manager",
    "Therapist, music",
    "Primary school teacher",
    "Archivist",
    "Health and safety adviser",
    "Research scientist (life sciences)",
    "Veterinary surgeon",
    "Data scientist",
    "Media buyer",
    "Museum/gallery exhibitions officer",
    "Health promotion specialist",
    "Farm manager",
    "Warehouse manager",
    "Surgeon",
    "Illustrator",
    "Biomedical scientist",
    "Logistics and distribution manager",
    "Geologist, wellsite",
    "Operational investment banker",
    "Private music teacher",
    "Occupational psychologist",
    "Building services engineer",
    "Bookseller",
    "Engineer, technical sales",
    "Neurosurgeon",
    "Museum/gallery conservator",
    "Garment/textile technologist",
    "Systems analyst",
    "Therapist, sports",
    "Art gallery manager",
    "Retail banker",
    "Radiographer, diagnostic",
    "Editor, magazine features",
    "Teacher, adult education",
    "Water engineer",
    "Clinical cytogeneticist",
    "Air cabin crew",
    "Oceanographer",
    "Research scientist (maths)",
    "Psychotherapist, child",
    "Public house manager",
    "Chief Technology Officer",
    "Planning and development surveyor",
    "Pharmacologist",
    "Scientist, research (physical sciences)",
    "Ecologist",
    "Tree surgeon",
    "Engineer, drilling",
    "Art therapist",
    "Architectural technologist",
    "Equities trader",
    "Production assistant, television",
    "Field seismologist",
    "Musician",
    "Designer, multimedia",
    "Nutritional therapist",
    "Designer, television/film set",
    "Tax inspector",
    "Public librarian",
    "Loss adjuster, chartered",
    "Accountant, chartered certified",
    "Merchandiser, retail",
    "Sports development officer",
    "Interpreter",
    "Homeopath",
    "Engineer, aeronautical",
    "Analytical chemist",
    "Energy manager",
    "Community arts worker",
    "Management consultant",
    "Public relations officer",
    "Ship broker",
    "Chemist, analytical",
    "Environmental manager",
    "Product manager",
    "Education officer, community",
    "Field trials officer",
    "Restaurant manager, fast food",
    "Broadcast journalist",
    "Secretary/administrator",
    "Company secretary",
    "Sports administrator",
    "Producer, television/film/video",
    "Barista",
    "Advertising copywriter",
    "Immigration officer",
    "Hydrogeologist",
    "Clinical psychologist",
    "Solicitor, Scotland",
    "Contracting civil engineer",
    "Engineer, manufacturing",
    "Psychiatric nurse",
    "Water quality scientist",
    "Surveyor, rural practice",
    "Environmental education officer",
    "Operational researcher",
]
